### ISSUE TITLE
Problem 1

### ISSUE THREAD

**Issue by jybluekim** [ajkim0630/Project_Euler#1]
A few things seem not right.

Prob says:
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.

Looking at your code it seems like you are counting numbers that meet the criteria but you need to be adding them. Plus do think about cases where a number is a multiple of BOTH 3 and 5.

Finally put everything in a func and add an answer at the top.

**Comment by ajkim0630** [comment]
fixed problem

**Comment by jybluekim** [comment]
Are you sure you did? What happens if a number is divisible by BOTH 3 and 5?
