### ISSUE TITLE
Prob 2

### ISSUE THREAD

**Issue by jybluekim** [ajkim0630/Project_Euler#2]
I see issues in prob 2. Maybe your function for fib number is correct but here they say add all the fib numbers (even valued). You are just counting something here. Seems wrong. 

Please fix it. 

====
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

**Comment by ajkim0630** [comment]
Okay, I will try to fix it with a list/dictionary or whatever.

**Comment by jybluekim** [comment]
Here is the trace you should see:

n, fib(n), sum 1 1 0
n, fib(n), sum 2 2 2
n, fib(n), sum 3 3 2
...
n, fib(n), sum 30 1346269 1089154
n, fib(n), sum 31 2178309 1089154
n, fib(n), sum 32 3524578 4613732

**Comment by ajkim0630** [comment]
I think I fixed it?

**Comment by jybluekim** [comment]
Close it if u think u fixed it.
