### ISSUE TITLE
Problem 3

### ISSUE THREAD

**Issue by jybluekim** [ajkim0630/Project_Euler#3]
I think project 3 is totally incomplete.

For a number, try to do prime factorization on the number and put the results in a dict or even a set. Once you are done with it, you can look at the numbers in the dict.keys() or set, then pick the largest one.

Don't close this issue till I confirm the answer.

**Comment by jybluekim** [comment]
What is going on here??

**Comment by ajkim0630** [comment]
I think I finished it?

**Comment by ajkim0630** [comment]
i am done with this
